# Generated by Django 3.1.7 on 2021-03-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210302_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='product test '),
            preserve_default=False,
        ),
    ]
