# Generated by Django 3.1.7 on 2021-03-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210303_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='discout_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
