# Generated by Django 3.1.7 on 2021-03-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20210309_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discount_price',
        ),
        migrations.AddField(
            model_name='item',
            name='discout_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
