# Generated by Django 3.1.7 on 2021-03-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20210310_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='dummyitem1'),
            preserve_default=False,
        ),
    ]
