# Generated by Django 3.1.7 on 2021-03-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sport wear'), ('OW', 'Outwear'), ('E', 'Electronics'), ('HA', 'Home accessories')], max_length=2),
        ),
    ]
