# Generated by Django 3.1.7 on 2021-03-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_order_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='billignaddress',
            name='apartment_address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
