# Generated by Django 3.1.7 on 2021-03-12 18:00

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_billignaddress_apartment_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billignaddress',
            name='countries',
        ),
        migrations.AddField(
            model_name='billignaddress',
            name='country',
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
